---
title: "EDA.Rmd"
output: html_document
---


# Notes:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eda coffee bean data}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(patchwork)
eda_df <- read.csv("eda_df.csv")
model_df <- read.csv("model_df.csv")
colnames(eda_df)
colnames(model_df)
```


```{r Plot Distributions}
## Numerical: Histogram
eda_df %>% ggplot(aes(x=Total.Cup.Points)) + geom_density()
eda_df$Non_Tropical <- as.factor(eda_df$Non_Tropical)
eda_df %>% ggplot(aes(x=altitude_mean_meters_adj, colour=Processing.Method)) + geom_density()
eda_df %>% ggplot(aes(x=altitude_mean_meters_adj, colour=Processing.Method)) + geom_density()
eda_df %>% ggplot(aes(x=mean_temp)) + geom_histogram()
eda_df %>% ggplot(aes(x=total_defects)) + geom_histogram()
eda_df %>% ggplot(aes(x=Quakers)) + geom_histogram()
```


```{r eda numerical features}
# Plot each feature relationship w/ Total.Cup.Points

## Numerical: Scatter plots
# Altitude
alt_points <- eda_df %>%
  ggplot(aes(x=altitude_mean_meters_adj, y=Total.Cup.Points)) + 
  geom_point() + geom_smooth(method = "lm")

# Temperature
temp_points <- eda_df %>%
  ggplot(aes(x=mean_temp, y=Total.Cup.Points)) + 
  geom_point() + geom_smooth(method = "lm")

# Total Defects
def_points <- eda_df %>%
  ggplot(aes(x=total_defects, y=Total.Cup.Points)) + 
  geom_point() + geom_smooth(method = "lm")

# Quaker Defects
quak_points <- eda_df %>%
  ggplot(aes(x=Quakers, y=Total.Cup.Points)) + 
  geom_point() + geom_smooth(method = "lm")

alt_points | temp_points | def_points | quak_points
```


```{r eda categorical features}
# Plot each feature relationship w/ Total.Cup.Points

## Categorical: Bar plots
# Variety
all_variety_points <- eda_df %>%
  ggplot(aes(x=Variety, y=Total.Cup.Points)) +
  stat_summary(fun.data=mean_sdl, geom="bar")

variety_points <- eda_df %>%
  ggplot(aes(x=variety_adj, y=Total.Cup.Points)) +
  stat_summary(fun.data=mean_sdl, geom="bar")

all_variety_points | variety_points

# Processing Method
proc_points <- eda_df %>%
  ggplot(aes(x=Processing.Method, y=Total.Cup.Points)) +
  stat_summary(fun.data=mean_sdl, geom="bar") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# Tropical (0) vs. Non-Tropical (1)
trop_points <- eda_df %>%
  ggplot(aes(x=Non_Tropical, y=Total.Cup.Points)) +
  stat_summary(fun.data=mean_sdl, geom="bar")

# Harvest Year
year_points <- eda_df %>%
  ggplot(aes(x=Harvest.Year, y=Total.Cup.Points)) +
  stat_summary(fun.data=mean_sdl, geom="bar")

proc_points | trop_points | year_points
```







